# Generated by Django 5.2.8 on 2025-11-16 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cover',
            field=models.ImageField(default='images\\default.jpg', upload_to='\\images'),
        ),
    ]
